/**
 * Human-facing references: base32-ish, no vowels, so no reference ever spells a
 * word or gets misread over the phone. Web Crypto, so no dependency.
 */
export function reference(prefix: string): string {
  const alphabet = '23456789BCDFGHJKLMNPQRSTVWXZ'
  const bytes = crypto.getRandomValues(new Uint8Array(6))
  return `${prefix}-${Array.from(bytes, (b) => alphabet[b % alphabet.length]).join('')}`
}

/**
 * Primary keys for rows written as raw SQL.
 *
 * Prisma's `@default(cuid())` is generated by the client, not by Postgres —
 * `information_schema` shows no default on a single `id` column — so anything
 * inserted outside Prisma has to bring its own. Existing rows keep their cuids;
 * these are UUIDs. Both are opaque strings and nothing parses them.
 */
export function newId(): string {
  return crypto.randomUUID()
}
